### ISSUE TITLE
Morning session

### ISSUE THREAD

**Issue by Rocio01** [Rocio01/Using-Bootstrap#1]

**Comment by harshdeepkanhai** [comment]
The top margin causes extra space which is not needed.

https://github.com/Rocio01/Using-Bootstrap/blob/4181b81d51e6debaede8cc128f8f3ea0c6ee54c4/css/style.css#L231


Also, the webpage is not centered in the screen having a width larger than 1200px (for L 1440px and 2K 2560px)
![image](https://user-images.githubusercontent.com/61924625/86931757-b38b6900-c0f5-11ea-9633-bbde37d039ef.png)

On smaller screens, the navigation menu is not aligned.
![image](https://user-images.githubusercontent.com/61924625/86931613-88087e80-c0f5-11ea-907e-e1ce8dc0fb35.png)

**Comment by Prabhakarzx** [comment]
## Thank you for the review @harshdeepkanhai :+1: 
### We've fixed the pointed out issues
# Thanks! :bouquet:
